#!/bin/bash

if ! command -v python3 &> /dev/null; then
    echo "Warning: python3 could not be found. Please install Python 3 to run Thot."
    exit 1
fi

file=$1
thotpy="$(readlink -f ~/.local/bin/thot).py"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$file" ]; then
    /usr/bin/python3 $thotpy 
elif [ -f "$file" ]; then 
    /usr/bin/python3 $thotpy "$file"
else
    echo "Error: File '$file' does not exist."
    exit 1
fi
